# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3.0.0
          
        - name: acessando ec2
          run: ssh app@15.228.3.165
          
        - name: Mostrando directorio
          run: ls
