name: Deploy AWS

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Copia del projecto
        uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: rusrushal13/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          targets: '[{ "Key": "tag:Name", "Values": ["ec2"] }]'
          comment: aws-ssm-send-command testing
          working-directory: /home/ubuntu/
          command: echo $(date) >> logs.txt
  
          
