name: Deploy heroku
on: 
 push:
    branches: staging
 pull_request:
    branches: staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HERORKU_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: devinsalesdploy
