name: Deploy Heroku
on: 
  pull_request:
     branches: staging  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HERORKU_KEY }} # your  heroku api key
          app_name: Devin-Sales-Deploy # you aplication name
          dockerfile_path: '.' # set the path to the folder wher the Dokerfile is located
    
